// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SeeMe",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "SeeMe",
            targets: ["AppModule"],
            bundleIdentifier: "com.francesco.academy.SeeMe",
            teamIdentifier: "4BNM7WSTN5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "App uses the camera to let you store a memory of your story."),
                .fileAccess(.pictureFolder, mode: .readWrite),
                .fileAccess(.userSelectedFiles, mode: .readWrite)
            ],
            appCategory: .entertainment
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)